title: Kerala IoT Challenge
email: rahulskumar2002@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This page is used to keep track of the experiments 
baseurl: "Kerala-IoT-Challenge" # the subpath of your site, e.g. /blog
theme: jekyll-theme-cayman
github:
  is_project_page: false
